const { onDocumentCreated } = require('firebase-functions/v2/firestore');
const { getFirestore } = require('firebase-admin/firestore');
const { generateSummarizationPrompt } = require('../services/ai.service');

// Firestore trigger on new chat message
exports.onChatMessage = onDocumentCreated('rooms/{roomId}/chatMessages/{messageId}', async (event) => {
  const snapshot = event.data;
  if (!snapshot) return;

  const data = snapshot.data();
  const roomId = event.params.roomId;
  const db = getFirestore();

  // If the message is already generated by AI, ignore it to prevent loops
  if (data.isAI) return;

  // Let's assume users can ping @WatchProAI
  if (data.text && data.text.includes('@WatchProAI')) {
    
    // Fetch last 15 messages for context
    const recentMessagesSnap = await db.collection('rooms')
                                       .doc(roomId)
                                       .collection('chatMessages')
                                       .orderBy('createdAt', 'desc')
                                       .limit(15)
                                       .get();

    // Map the documents to a string for the prompt
    // Assuming messages are returned newest first, we reverse them
    const messagesArray = [];
    recentMessagesSnap.forEach(doc => {
      const msg = doc.data();
      // Skip the ping message itself so it doesn't skew context if needed, or include it
      messagesArray.push(`[${msg.createdAt ? new Date(msg.createdAt.toDate()).toLocaleTimeString() : 'Unknown'}] ${msg.userId}: ${msg.text}`);
    });
    
    // Reverse to chronological order
    const contextString = messagesArray.reverse().join('\n');

    // Call external AI API
    const replyText = await generateSummarizationPrompt(contextString);

    // Save AI reply back into the chat as an AI actor
    await db.collection('rooms').doc(roomId).collection('chatMessages').add({
      userId: 'watchpro_ai', // System identity
      name: 'WatchPro AI',
      text: replyText,
      createdAt: new Date(),
      isAI: true,
      reactions: {}
    });

    console.log(`Executed AI ping in room ${roomId}. Context evaluated.`);
  }

  return null;
});
