import { useState, useEffect } from 'react';
import { generateSessionRecap } from '../services/gemini';
import { Loader } from 'lucide-react';

export default function SessionRecapModal({ chatMessages = [], videoContext = '', onClose }) {
  const [recap, setRecap] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    async function fetchRecap() {
      try {
        if (chatMessages.length === 0) {
          throw new Error("No chat logs available to summarize.");
        }
        const history = chatMessages.slice(0, 50).reverse().map(m => ({
          time: (m.createdAt?.toDate ? m.createdAt.toDate() : new Date()).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
          name: m.userName || 'Unknown',
          text: m.text
        }));

        const result = await generateSessionRecap(history, videoContext);
        setRecap(result);
      } catch (err) {
        console.error(err);
        setError(err.message || "Failed to generate AI recap. Check your Gemini API key in Settings.");
      } finally {
        setLoading(false);
      }
    }
    
    fetchRecap();
  }, [chatMessages, videoContext]);

  return (
    <div className="modal-backdrop" onClick={onClose}>
      <div className="modal recap-modal" onClick={e => e.stopPropagation()}>
        <div className="modal-header">
          <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
            <span style={{ fontSize: '1.5rem', background: 'var(--accent-soft)', padding: 8, borderRadius: 12 }}>✨</span>
            <div>
              <h2 className="modal-title">AI Session Recap</h2>
              <div style={{ fontSize: '0.75rem', color: 'var(--text-muted)', marginTop: 2 }}>Generated by WatchPro AI</div>
            </div>
          </div>
          <button className="icon-btn" onClick={onClose}>✕</button>
        </div>

        {loading ? (
          <div style={{ padding: '40px 20px', display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 16, color: 'var(--text-secondary)' }}>
            <Loader className="rotate" size={24} />
            <div style={{ fontSize: '0.9rem' }}>Analyzing chat logs & reading the room's vibe...</div>
          </div>
        ) : error ? (
          <div style={{ padding: '40px 20px', color: '#f87171', textAlign: 'center', fontSize: '0.9rem' }}>
            {error}
          </div>
        ) : recap ? (
          <>
            <div className="recap-section animate-fadeIn">
              <div className="recap-label">Plot Summary</div>
              <div className="recap-text">{recap.plotSummary}</div>
            </div>

            <div className="recap-section animate-fadeIn" style={{ animationDelay: '0.1s' }}>
              <div className="recap-label">Group Vibe</div>
              <div className="recap-text">{recap.groupVibe}</div>
            </div>

            <div className="recap-section animate-fadeIn" style={{ animationDelay: '0.2s' }}>
              <div className="recap-label">Top Highlights</div>
              <div className="highlight-list">
                {recap.highlights?.map((h, i) => (
                  <div key={i} className="highlight-item">
                    <div className="highlight-dot" />
                    <div>
                      <strong>{h.time}</strong> — {h.text}
                    </div>
                  </div>
                ))}
              </div>
            </div>

            <div className="animate-fadeIn" style={{ animationDelay: '0.3s', marginTop: 24, padding: 16, background: 'var(--bg-tertiary)', borderRadius: 'var(--radius-lg)', display: 'flex', alignItems: 'center', gap: 12 }}>
              <div style={{ fontSize: '2rem' }}>🍿</div>
              <div>
                <div style={{ fontSize: '0.85rem', fontWeight: 600 }}>Up Next Recommendation</div>
                <div style={{ fontSize: '0.75rem', color: 'var(--text-secondary)', marginTop: 4 }}>Based on this session, WatchPro AI recommends: <strong>{recap.recommendation}</strong></div>
              </div>
              <button 
                className="btn-primary" 
                style={{ marginLeft: 'auto', padding: '6px 14px', fontSize: '0.75rem' }}
                onClick={() => alert(`Normally this would switch to: ${recap.recommendation}`)}
              >
                Queue It Up
              </button>
            </div>
          </>
        ) : null}
      </div>
    </div>
  );
}
